- Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
Readds some nitrogen tanks that were deleted in previous PR. To reduce bloat, oxygen tanks in most lockers have been replaced with air tanks to allow slimepeople to breathe.
The guide about slimepeople in species guides might need to be reworked to accommodate this change.
To allow slimes to breathe.
A simple change of yml file codes. Oxygen tanks in most lockers have been replaced with Air tanks (`OxygenTankFilled` -> `AirTankFilled`). Also readds some emergency nitrogen tank code that were removed after that PR.
**Changelog**
:cl:
- Readded emergency nitrogen tanks in emergency toolboxes or some lockers.
- Replaced oxygen tanks with air tanks in most lockers.
> Readds some Nitrogen tanks, while replacing some locker oxygen tanks with air tanks.

- Resources/Locale/Ronstation/en-US/ghost/roles/ghost-role-component.ftl
- Resources/Prototypes/Entities/Mobs/Player/skeleton.yml
- Resources/Prototypes/Ronstation/Roles/Jobs/Fun/misc_startinggear.yml
Self explanatory; made the closet skeletons non-antags. Also gave them a PDA, headset, and a backpack.
Right now, closet skeletons are considered "neutrals" with a description that states that they can also "wage a skeletal war", which allows them to kill people without repercussions, allowing them to wreak havoc on the station (imagine if one spawned inside an armory locker, acquires all the weaponry, and proceeds on a murder spree, ruining the round). This can make them popular not only with 'shitters', but also raiders. This PR changes the closet skeletons' description, so they are now supposed to act as crewmembers and not kill people; those who kill people without permission from the administration will face administrative action.
On the other hand, the reason why they will be …
> Make closet skeletons crewmates while also adding a bunch of necessities to them.

- Resources/Locale/en-US/tools/tool-qualities.ftl
- Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
- Resources/Prototypes/Tiles/plating.yml
- Resources/Prototypes/tool_qualities.yml
Gives a new tool quality, “Axing”, applied to atmospheric fireaxes.
right now, there was no way to pry plating tiles, so if you made a mistake of applying a plating tile to a lattice tile, you can’t reverse it without having to use a limited-charge RCD. We have determined that the best tool for the job as an atmospheric technician’s fireaxe, as it is usually only available for atmospherics engineers and not regular passengers with crowbars. If very common tools such as crowbars were able to pry plating, the station would be quickly made uninhabitatable, due to either shitters, raiders, free-agents, or antagonists prying open plating, spacing a lot of rooms.
**Changelog**
:cl:
- add: Created “Axing” quality, and applied it to an atmospheric technician’s fireaxe.
> Give atmos fire axe ability to pry tiles.

- Resources/Prototypes/Ronstation/Entities/Mobs/NPCs/animals.yml
Modifies the directory path used to find syndimothroach textures to the correct configuration.
Current syndimothroach directory is incorrect, resulting in this:
This PR fixes this error.
**Changelog**
:cl:
- fix: Fixed syndimothroach texture path in prototypes.
> Fix syndimothroach texture path in prototypes.

- Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
a small change in xenos. they became more valuable.
a new way for salvage getting money. there's usually alot of burrowers at Mars (AKA the big distant asteroid), so i buffed their health by 15. you now require 3 shots (or 2 shots and 1 stab if you're kool enough) to kill a burrower.
no
- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
no
**Changelog**
Xenos are now more valuable.
> xeno change

- Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
Debuffs goliath
Roundstart hardsuits for salvage already suck due to it's slow speed, and goliaths spawn in pairs or alone, hell for any lone cargo technician or salvager
Lowers speed, damage, attack speed and health
> Goliath debuff

- Resources/Locale/en-US/tools/tool-qualities.ftl
- Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
- Resources/Prototypes/Tiles/plating.yml
- Resources/Prototypes/tool_qualities.yml
Allows the atmospheric technician’s fire axe to pry open plating. The syndicate fireaxe would still not be able to pry fire axe.
Readds https://github.com/RonRonstation/ronstation/pull/45 and https://github.com/RonRonstation/ronstation/pull/46.
Currently, there is no way to pry open plating tiles to turn it into lattice, however, sometimes you need to undo the placement of plating, especially when you did so on mistake.
The atmospheric technician’s fire axe should be given the privilege of being able to pry open plating, not only because of how only qualified engineers can get it (not even technical assistants, interns of engineering, can get it), but because there is currently no way to pry open plating. Besides, it’s the atmospheric technician’s job to fix atmospheric issues.
The …
> Allow atmos fire-axe to pry plating.

- Resources/Locale/en-US/reagents/meta/chemicals.ftl
- Resources/Prototypes/Reagents/chemicals.yml
- Resources/Prototypes/Recipes/Reactions/chemicals.yml
- Resources/Prototypes/Recipes/Reactions/fun.yml
Removes the recipe for Ammoniated Sludge and makes it a byproduct of Ammoniated Mercury, adds Calomel.
More chems for more recipes in the future, makes ammoniated sludge not entirely useless.
> Calomel and Ammoniated Mercury

- Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
- Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
- Resources/Prototypes/Ronstation/Access/engineering.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Devices/door_remote.yml
- Resources/migration.yml
- Gives firelocks the ability to be bolted.
- Adds a fire-fighting remote inside atmospheric technician's lockers; they can only be used by atmospheric technicians.
I might add a bolt wire to firelocks soon.
Firelocks, if they're made in real-life, are supposed to be bolted upon, once it's closed after a spacing or other atmospheric issue occurs, so it can use the entire strength to prevent such issues from spreading further. Besides, it should help with not wasting so much time trying to holofan a big leak, as they expire within a short period and also their projectors have a limited charge (6 charges). On the other hand, if you weld during a tritium and plasma leak, the flame from that welder can cause the plasma or tritium within that chamber to go on fire, potentially leading to more …
> Rework firelocks.

- Content.Shared/Atmos/Atmospherics.cs
- Resources/Prototypes/Atmospherics/gases.yml
changes the price per mole for n2o and frezon, which made n2o and frezon pratically useless except for gas flooding and that one heat generator thing
wizden contrishitter PRs go go away
> atmospherics changes

- Resources/Prototypes/Entities/Structures/Power/Generation/teg.yml
- Resources/Prototypes/Ronstation/Catalog/Cargo/cargo_engines.yml
- Resources/Prototypes/Ronstation/Catalog/Fills/Crates/engines.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/engines.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Devices/flatpack.yml
Adds TEG flatpacks, and associated circuitboards, and adds them to the cargo catalog.
Currently, the TEG is the only power generator, besides the infinite power generators, that you cannot build or deconstruct, which is rather odd.
This PR was made because 1 user requested that this be made.
**Changelog**
:cl:
- add: Added TEG flatpacks, and associated circuitboards, and adds them to the cargo catalog.
> Add TEG flatpacks and put them on the market.

- Resources/Locale/en-US/ronstation/research/technologies.ftl
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Ronstation/Research/civilianservices.yml
added cloning research as a civ tier 3 thingie
cloning was murdered by wizden, this PR resurrects it
no
**Changelog**
You can now research cloning. It's a tier 3 civ tech.
> cloning research

- Resources/Prototypes/Reagents/medicine.yml
- Resources/Prototypes/Recipes/Reactions/medicine.yml
Slightly changes the recipe for opporozidone and gives it a small buff.
Opporozidone - " a difficult to synthesize cryogenic drug", requires at least more than 50 units to reverse half of the rotting on a dead person, keep in mind though, that rotting people generally have _(some)_ genetic/poison damage, and some other damage in high quantity too, which is almost impossible to heal without more cryogenic chemicals/high amounts of topicals.
This makes it a bit more rewarding, since it requires less reagents _(requires 1 more part of doxarubixadone)_ to make, and opporozidone to fully rejuvenate a corpse.
> opporozidone buff

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Lathes/biogen.yml
Instead of begging chemistry, botany can now make their own potassium, phosphorus, nitrogen, hydrogen and oxygen.
- Calcium hydroxide
- Barium hydroxide
- Magnesium hydroxide
- More...
> Biogenerator updates + new chemicals

- Resources/Locale/en-US/tips.ftl
- Resources/Prototypes/Roles/Jobs/departments.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Back/backpack.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Back/duffel.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Back/satchel.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Eyes/glasses.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Head/hats.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Head/soft.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Neck/misc.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Shoes/boots.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpskirts.yml
- Resources/Prototypes/Ronstation/Entities/Clothing/Uniforms/jumpsuits.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Devices/Electronics/door_access.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Devices/radio.yml
- Resources/Prototypes/Ronstation/Entities/Objects/Misc/identification_cards.yml
- Resources/Prototypes/Ronstation/Entities/Objects/base_contraband.yml
- Resources/Prototypes/Ronstation/Entities/Structures/Doors/Airlocks/access.yml
- Fixes the numbering of a particular dataset.
- Fixes contraband on Terragov items.
- Moves Blueshield to Centcomm.
- This error came up, due to the number of our custom tip being overlooked, causing it and another one to have the same number. This resolves this issue.
- Somehow, an upstream PR caused the `allowedDepartments: null` in the contraband prototypes to cause error.
- Blueshield are supposed to be CentComm dignitaries, so their stuff should be CentComm contraband.
**Changelog**
:cl:
- fix: Fixed numbering of our custom tip being the same as another tip. 
- fix: Removed the `allowedDepartments: null`, as it’s causing errors.
- tweak: Blueshield items are now centcomm contraband.
- tweak: Blueshield airlocks are now centcomm airlocks.
> Fixes and other stuff.

- Resources/Locale/en-US/_Ronstation/reagents/cyanide.ftl
- Resources/Locale/en-US/_Ronstation/reagents/meta/chemicals.ftl
- Resources/Locale/en-US/_Ronstation/reagents/meta/elements.ftl
- Resources/Locale/en-US/_Ronstation/reagents/meta/medicine.ftl
- Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
- Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
- Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
- Resources/Prototypes/_Ronstation/Reagents/chemicals.yml
- Resources/Prototypes/_Ronstation/Reagents/elements.yml
- Resources/Prototypes/_Ronstation/Reagents/medicine.yml
- Resources/Prototypes/_Ronstation/Recipes/Reactions/chemicals.yml
- Resources/Prototypes/_Ronstation/Recipes/Reactions/medicine.yml
Additions:
- Chemicals:
Cyanide
Formaldehyde
Chloroform
Saltpetre
Caffeine
- Medicine:
Pentetic acid
Rezadone
Cordrazine
Salicylic acid
Spaceacillin (for one recipe)
Fun. Ports chemicals from the EE version to here.
Just YAML editing. Adds _Ronstation to Prototypes. Adds FTL folder for Locale.
none yet
Edits Prototypes/Reagents/Consumables/Drink/drinks.yml. May conflict at a later time.
> more chemistry + EE chem ports

- Content.Client/Power/APC/ApcVisualizerComponent.cs
- Resources/Prototypes/Entities/Structures/Power/apc.yml
- Resources/Prototypes/Entities/Structures/Power/substation.yml
Replaces substation and APC sprites to the ones we made.
Also readds https://github.com/RonRonstation/ronstation/pull/41 and https://github.com/RonRonstation/ronstation/pull/78.
As stated in https://github.com/RonRonstation/ronstation/pull/41, the current substation sprites that was added to upstream looked like it would be great as sprites for some telecommunications apparatus (or according to 1 user, some bulky circuit breaker thingy). It didn't help that it looked too similar to the Superconducting Magnetic Energy Storage (SMES) device, which can cause a bit of confusion. This aims to change the sprites, so we don't have to deal with people looking for the correct machine when someone tells them to "Go fix the substation!".
As for the APC sprites, they do look irritating. Their …
> Replaced Substation and APC sprites.

- Resources/Prototypes/secret_weights.yml
extended has been removed from the gamemode pool
survival has been reintroduced at 50% of it's previous rate
zombies and revs are twice as common as before
traitors is like 9.8% less common
extended literally does not function properly without admin intervention, it is *intentionally* designed this way, it *should not* roll naturally
survival, unlike extended, is *not* broken. yes, survival can be quite stressful, but it does *actually function*. stress can be fun sometimes, anyways
the absence of survival also contributes to shifts feeling more quiet then usual
we very rarely have the pop for zombies or revs, so they should be a bit more common, so they're more likely to roll when we *do* have the pop 
number -> other number
**Changelog**
> remove extended from the secret pool

- Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Paramedics now start with external access.
People dying in space is a headache for Paramedics. Removes some friction from the job while making them a bit more unique as a medical role that gets externals at the start of the round. 
Changes to the paramedic.yml file in Resources\Prototypes\Roles\Jobs\Medical
**Changelog**
:cl:
- Tweak: Paramedics now start with external access.
> Adds External access to the default access for Paramedics

- Resources/Prototypes/Procedural/Magnet/asteroid_ore_gens.yml
- Resources/Prototypes/Procedural/biome_ore_templates.yml
- Resources/Prototypes/Procedural/biome_ore_templates_low.yml
- Resources/Prototypes/Procedural/salvage_loot.yml
Salt ore deposits should no longer be generated in expeditions, and should be as rare as artifact fragments or bananium in asteroids.
The uses for the iodine and table salt produced by grinding salt ore are close to none. In the absence of a future chem rework in which chem must source most of its chemicals from the station, salt ore only exists to be thrown into space or clog up mining bags.
This pull request is being made as the result of a suggestion poll, 12 - 2 for removing the ore.
Commented out relevant lines in biome_ore_templates.yml and biome_ore_templates_low.yml and reduced the weight of OreSalt in asteroid_ore_gens.yml
**Changelog**
:cl:
- tweak: Salt ore deposits will no longer be generated on expedition maps, and has a much lower chance of appearing in asteroids.
> Removes salt ore deposits from expeditions and lowers the chance of it appearing in asteroids

- Resources/Locale/en-US/stack/stacks.ftl
- Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
- Resources/Prototypes/Recipes/Lathes/Packs/security.yml
- Resources/Prototypes/Recipes/Lathes/security.yml
- Resources/Prototypes/Stacks/medical_stacks.yml
Before, tourniquets sucked ass and could literally kill you. Not anymore.
Tourniquets now heal 2 slash & 2 piercing, take away 5 points of bleeding (of 10 total possible), take 2 seconds to apply to another and 4 seconds to apply to yourself, and stack up to 5.
The security techfab can now manufacture 1 tourniquet for 0.1 steel and 0.25 plastic.
This is changed from:
Tourniquets _dealing_ 5 of all brute (????!!) and 5 asphyxiation, taking away 10 points of bleeding, taking 0.5 seconds to apply to another and 1.5 seconds to apply to yourself, and not stacking at all.
Tourniquets being obtainable only as randomized table/locker clutter and in the SecTech vending machine.
Tourniquets were a laughably bad ""feature"" that nobody ever, ever, _ever_ interacts with. The only purpose they served …
> Make tourniquets actually good and useful and accessible 

- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
Adds 5-07 Paradoxical Existence criminal charge to space law, pending rework of paradox clones.
In a paradox situation, the original character has very few counterplays to a hostile clone. If you fight back you are assumed to be the clone, getting distance from a clone is often infeasible, et cetera. This pull request adds an in-character avenue for paradox clone counterplays, pending a rework of paradox clones where they are not categorically hostile.
It is currently much, much more fun to role abandon as a paradox clone, ignoring your sole kill objective, but that is another issue, pending a rework and separate PR.
Additions to one xml guidebook file.
**Changelog**
:cl:
- add: Space Law now features a 5-07 Paradoxical Existence criminal charge
> 5-07 Paradoxical Existence space law criminal charge

- Resources/Changelog/Changelog.yml
- Resources/Locale/en-US/reagents/meta/medicine.ftl
- Resources/Prototypes/Reagents/medicine.yml
- Resources/Prototypes/Recipes/Reactions/medicine.yml
This reverts commit 02fe5b4ac544bbf9b868e043ac1179663229f5f0.
Reverts reversion of new cryonics because new cryonics is good, actually.
Wizden maints can't design a videogame.
I <3 nu cryonix.
New cryonics may receive proper rebalancing in the future, if deemed necessary by us.
Reversion of one (1) hotfix commit.
> Revert reversion of new cryonics

- Resources/Prototypes/Entities/Mobs/Species/vox.yml
- Resources/ServerInfo/Guidebook/Mobs/Vox.xml
Raises Vox passive healing threshold to 50 total damage, up from 20; and adds cold, shock, & radiation damage passive healing.
Updates Vox guidebook entry to reflect these values.
Some people who don't play Vox were being spacist to Vox because they have no "advantage" to 'compensate' for O2 toxicity.
6 lines of yaml changes. Rewritten paragraph in guidebook xaml.
**Changelog**
:cl:
- tweak: Vox now regenerate more damage types, below 50 total damage.
> Enrobustify Vox slightly

- Resources/Prototypes/Objectives/objectiveGroups.yml
Removed the warden hat objective from the objective's group and added the new warden's whistle objective. 
Bugfix for pr https://github.com/RonRonstation/ronstation/pull/274. Occasionally we could roll a non-existent objective and the server would not like that. We also *couldn't* roll the new objective, since it wasn't in the objectives group. We should be able to do that now.
changes to objectiveGroups.yml
- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl:
- fix: Warden Whistle objective had a bug preventing it from being rolled, and now should be able to be …
> (Bugfix) Add whistle to objectivegroups, remove now gone warden hat objective

- Resources/Locale/en-US/_Ronstation/ghost/ghost-role-component.ftl
- Resources/Locale/en-US/_Ronstation/research/technologies.ftl
- Resources/Locale/en-US/_Ronstation/station-events/events/bureaucratic-error.ftl
- Resources/Locale/en-US/_Ronstation/store/uplink-catalog.ftl
- Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
- Resources/Locale/en-US/research/technologies.ftl
- Resources/Locale/en-US/station-events/events/bureaucratic-error.ftl
- Resources/Locale/en-US/store/uplink-catalog.ftl
Moved all of the strings we've edited in upstream .ftl files into our own subdirectories. Restored the free agent status of the giant tarantulas.
Due to https://github.com/RonRonstation/ronstation/issues/296, we had to add a lot of comments to modified content in upstream files. In the course of doing this, I did not realize that you could not add inline comments to the strings in these .ftl files, causing these comments to show up in game erroneusly. To fix this, all modified strings have been moved into appropriate .ftil files and file paths under the _Ronstation subdirectory in en-US (which probably should have been the solution in the first place), and strings that were modified from upstream were restored and commented out. 
In the course of doing this, I realized that the change to …
> Fix inline licensing comments appearing in some in-game text

- Resources/Prototypes/GameRules/events.yml
Wizard now requires a minimum player count of 25 to spawn.
We've had a streak of low population games spectacularly ruined by vicious wizards lately. We've gotten lucky in the past that a lot of our players have tried to be interesting with the role on lower player counts, but given that upstream is already looking at doing this, and that currently wizard requires a measly 10(?!) players to spawn currently, it feels like a good idea to change this. If the mood changes, there's a rework upstream, or we manage to pull off a rework ourselves, then this shouldn't be a difficult number to tweak back down in the future.
events.yml parameter for the BaseWizardRule has changed
- [ X ] I have read and am following the [Pull Request and Changelog …
> Raises minimum players required for the wizard spawn to 25

- Resources/Prototypes/Guidebook/shiftandcrew.yml
- Resources/ServerInfo/Guidebook/Jobs.xml
- Resources/ServerInfo/_Ronstation/Guidebook/Jobs.xml
I reordered the list of jobs under the jobs in the guidebook to be alphabetical instead.
I also mentioned paramedics are a part of the medical department under the general jobs overview.
The current ordering is rather arbitrary.
Paramedics are currently not mentioned in the general job overview.
No balance changes.
All text changes.
None.
**Changelog**
> Guidebook Job ordering change

- Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs
- Content.Server/StationEvents/Events/VentCrittersRule.cs
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/GameRules/pests.yml
- Un-hardcoded several vars in the VentCrittersRuleComponent, allowing us to set the scaling and amount of critters on an individual basis.
- Added a var for the number being used as the floor for calculating how many creatures to spawn. Set that floor to 3 by default, as opposed to the 1 it was before
- Modified the calculation determining how many critters spawn to include a ceiling for how many critters can spawn, and added an accompanying var in the VentCrittersRuleComponent
- Changed the base scaling, min, and max of the calculation to increase the number of spawns.
- Modified the prototypes of the pest spawning events to allow for higher numbers of them to spawn.
- Re-added the dreaded clown-spider spawn event. Modified vars to make them less numerous when they spawn compared to …
> Vent Critters post-factum changes

- Resources/Prototypes/Maps/Pools/default.yml
Adds NT-ACS Atlas 3 Installation & NT-TE Feint Station to the default maps pool. Making them available for vote between their designated player thresholds.
After the latest set of patches for both maps, I consider them stable enough for live rotation, as their architect. We still have the forum threads for any new issues that crop up, and I will continue making patches to them as long as me and the maps are here.
One (1) yml file edited.
**Changelog**
:cl: arenaconspiracy
- add: The map Atlas 3 is now available for vote between 0 and 35 players.
- add: The map Feint Station is now available for vote between 15 and 35 players.
> Add Atlas 3 & Feint Station to rotation

- Resources/Prototypes/Guidebook/rules.yml
- Resources/ServerInfo/_Ronstation/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml
A revision of RP rule 4 making what is commonly referred to as "new life rule" (NLR) formally enforceable under LRP.
The PR changes one line of text in roleplay rule 4, which originally says "MRP Amendment", and replaces it with "Knowledge gained in crit, knowledge lost upon death", removing the MRP language entirely.
We have always expected players to commit to NLR, but never adjusted the rules to support it until now. Stealing an item off a player as traitor (which may require killing them) is very difficult to get away with if the person you killed can just turn around and tattle on you when revived.
**Changelog**
:cl:
- tweak: New life rule is no longer an MRP amendment, and is enforced under LRP.
> Make new life rule enforced under LRP

- Resources/Locale/en-US/ronstation/ghost/roles/ghost-role-component.ftl
- Resources/Locale/en-US/ronstation/store/uplink-catalog.ftl
- Resources/Prototypes/Ronstation/Catalog/uplink_catalog.yml
- Resources/Prototypes/Ronstation/Entities/Mobs/NPCs/animals.yml
Makes syndimothroaches spaceproof.
Buffs their attack power (4 slash + 6 piercing, 15 structural)
Makes them insulated (shockproof)
Lowers their price in the uplink (3 base cost, 2 on discount, from 5 base 4 discount)
Makes them unimplantable (syndimoth + minibomb is just a better syndicat, that should not be possible)
Syndimothroaches now have an actual use beyond admin spawns and cute bait. They still die in 5 swings of a crowbar.
Currently, syndimothroaches are _entirely_ useless. They deal a whopping eight (8) damage to people and do absolutely nothing else, for the low low price of a quarter of a traitor uplink. And (and) they die near instantly in space, ergo they are entirely useless to nuclear operatives.
This PR makes them able to at the very least chew through wires without …
> Make SyndiMothroaches not useless

- Resources/ConfigPresets/Build/development.toml
Edits 2 lines in Resources/ConfigPresets/Build/development.toml to disable randomized characters & mob collisions because I prefer it that way.
Having the edited file in my git worktree all the fucking time is pissing me off.
N/A
N/A
**Changelog**
= tweak : FUCK!
> Disable randomized characters & mob collisions on the dev build in config

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Makes butterflies immune to romerol infection.
Similar creatures either cannot infect you or are themselves immune to romerol. The closest comparison was the bee mob, which is zombie immune, so I gave butterflies zombie immune to fix what I presume is an oversight.
Adds a component to MobButterfly in animals.yml.
N/A
N/A
**Changelog**
:cl:
- tweak: Butterflies can no longer be infected with romerol or become romerol zombies
> Make butterflies Zombie Immune

- Resources/Prototypes/Species/skin_colorations.yml
- Resources/Prototypes/Species/vulpkanin.yml
Vulp colors have been clamped further and hair colors have been set to follow skin color.
They were requested changes to make some more comfortable with vulpakanin.
N/A
**Changelog**
:cl:
- tweak: Vulpakanin colors have been clamped significantly, and hair color for vulpakanin now follows skin color.
> Clamp Vulp colors further
