RonRonstation/ronstation

Content.Shared/CCVar/CCVars.cs

There has been times when a single "no" vote resulted in the vote failing to pass, even though the round is so messed up (either due to raiders or some other event) that a restart is necessary. This aims to put the restart vote ratio in CCVars.cs from 85 to 70, per Ronnie's suggestion.
To allow us to restart when raiders or some other event messes an event so hard it's bad.
Changed restart vote ratio in CCVars.cs from 85 to 70.
**Changelog**
- Reduced restart vote ratio from 85 to 70.

Reduced restart vote ratio to 70.

---

Resources/Prototypes/game_presets.yml

Sometimes, we miss the old days when sandbox was still available. This aims to allow sandbox to be voteable again.
We can play a bit of Sandbox. Just needs some extra admin monitoring to prevent entity spam or mass destruction.
**Changelog**
:cl:
- Made sandbox voteable again.

Allow sandbox to be voteable again.

---

Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml

Air tanks have nitrogen, and emergency nitrogen tanks have been readded, so that info is obsolete.
Ever since Pull #10 (which is a fix of pull #4), that info about nitrogen being hard to find compressed in tanks, is obsolete.
The fixes made that info obsolete. It's time to remove that info.
**Changelog**
:cl:
- remove: Removed obsolete info.

Removed obsolete info in Slimeperson guide.

---

Content.Shared/CCVar/CCVars.cs

This aims to bring back map votes.
We are a lowpop server, and there is a chance we get stuck in unfavorable maps, be it medium-high population maps such as Boxstation or Metastation, or niche maps such as Train. A map vote should resolve this issue.
The `vote.map_enabled` is set to `true` to enable map votes.
**Changelog**
:cl:
- tweak: `vote.map_enabled` is set to `true`, enabling map votes.

Allow Map Votes.

---

Resources/Locale/en-US/species/species.ftl
Resources/Prototypes/Species/gingerbread.yml

There was a bug that caused gingerbread people to be named as "humans". This not only makes no sense, but causes confusion. This PR aims to fix that bug.
This naming mishap could cause confusion, especially during character creation. This PR should eliminate any confusion.
**Changelog**
:cl:
- fix: Fixed gingerbread people name from "human" to "gingerbread person".

Renames gingerbread people from "human" to "gingerbread person".

---

Content.Shared/CCVar/CCVars.cs

It has been discovered that ahelp messages are not being recorded on the ahelps channel, because the CCVars to enable ahelps to be relayed to the ahelps channel on our discord servers have not been set up. This PR aims to fix this. 
For record-keeping reasons. It might also allow some in the administration to respond if possible, should someone send an ahelp message.
The link is a webhook that will allow relays to a specific discord channel.
**Changelog**
:cl:
- fix: Added we hook in CCVars to relay ahelp messages to a specialized discord channel.

Webhook ahelps channel.

---

Resources/Audio/Lobby/attributions.yml

I found out a factor of why YAML thingies keep on failing; the urls in lobby attribution files are set to “Unknown”, which is not a url, causing errors.
Bug fix. It’s also due to copyright reasons either.
The url sections are added with true urls instead of “unknown”s, fixing a bug that is one of the causes for YAML to fail.
**Changelog**
:cl:
- fix: Fixed attributions being just “unknowns”, replacing them with full credits.

Fix lobby attributions.

---

Resources/Prototypes/Species/human.yml

I changed the human.yml to allow headtop and tail markings.
Fun, and also to allow even more character customization.
The headtop and tail marking points are increased from 0 to 1, to allow use of headtop and tail markings.
As there were no headtop and tail sprite layers, such layers have been added to allow the markings to show up as sprites.
**Changelog**
:cl:
- add: Added head top and tail marking sprite layers.
- tweak: Redid headtop and tail marking points from 0 to 1.

Added headtop and tail markings.

---

Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
Resources/Prototypes/Entities/Objects/Decoration/present.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/arcades.yml

Since blackburn items are merged, the items need to spawn, besides admin intervention.
The blackburn clothing will have to be done in loadouts in a separate PR.
Fun.
**Changelog**
:cl:
- tweak: Allowed blackburn items to spawn.

Allow blackburn items to spawn.

---

Resources/Prototypes/Species/human.yml
Resources/Prototypes/game_presets.yml

This readds 2 PRs that was reverted during the "great reset of 2024". 1 about reenabling sandbox, another for extra customization.
We like sandbox; it's been 1 of our favorite gamemodes.
The head top and tail markings are to allow even more customization.
**Changelog**
:cl:
- tweak: Allowed sandbox to be voteable again.
- tweak: Allow headtop and tail markings.

Allow sandbox to be voteable again while also allowing headtop and tail markings.

---

Resources/Locale/Ronstation/en-US/ghost/roles/ghost-role-component.ftl
Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/Player/skeleton.yml

Fixes pull #32, in regards to closet skeleton description.
According to 1 coder:
> Locales aren't really meant to be used to theme the game like that, they're of course meant for languages. If you want to make a new one you'd make a new directory next to 'en' am such as 'fr' or 'ru'. If all you want to do is change some names and stuff you should just modify the ftl files, they're already so far removed from merge conflicts. Plus, you're modifying the Prototype anyway, which completely loses the benefits of using ftls. The whole point is that you don't need to modify YAML
By the way, using a new locale is a hardcoded string in the game somewhere, which is pretty lame. You'd switch that to change locale and you can only have one active at a time. I believe Russian servers have a fallback …

Fix closet skeleton description.

---

Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
Resources/Prototypes/Catalog/Fills/Crates/fun.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Resources/Prototypes/Entities/Objects/Decoration/present.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/arcades.yml
Resources/Prototypes/Ronstation/Clothing/Uniforms/jumpskirts.yml

Modified some prototypes to add blackburn items (the addition of blackburn items to the autodrobe meant a price increase is needed, due to arbitrage).
I have also fixed a typo related to the blackburn turtleneck skirt.
Fun.
**Changelog**
:cl:
- add: More ways for blackburn items to spawn.
- tweak: Increased price for autodrobe restock from 1200 to 1224 to prevent arbitrage.
- fix: Fixed a typo in blackburn turtleneck skirt prototype.

More blackburn spawns (and fixed a typo).

---

Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml

Turns DefaultRules.xml into a functional ruleset.
We need rules, like real rules. This one might be modified in the future.
Why did we modify `DefaultRules.xml` instead of switching to another ruleset? Because the host insisted on modifying `DefaultRules.xml` instead of changing the `rules_file` ruleset after a catastrophic mistake was made that caused the server to be offline.
**Changelog**
:cl:
- tweak: DefaultRules.xml now contains actual rules.

Added rules.

---

Content.Server/Ame/AmeNodeGroup.cs

Doubled AME power from 20000f to 40000f.
Right now, we have every station where there is only 1 core available, forcing people to use other more dangerous methods at power generation. Surely, we don't have to get people to beg for extra AME then receiving nothing because we aren't around.
This PR may be reverted when the the number of available AME cores on commonly used maps are doubled.
The AME power was doubled from 20000f to 40000f, not the overpowered 200000f that can make cutting cables dangerous. The reason is because it makes more sense having the AME feel like having 2 cores in a station that needs 2 cores to operate.
**Changelog**
:cl:
- tweak: Doubled AME power from 20000f to 40000f.

Doubled AME power until someone fixes the AME on the maps commonly used on the server.

---

Resources/Textures/Ronstation/Mobs/Animals/syndimothroach.rsi/meta.json

Fixes  the state names of syndimothroaches in the meta.json of the rsi folder from "syndiemothroach" to "syndimothroach".
It's causing RSI validators to fail.
**Changelog**
:cl:
- fix: Fixed syndimothroach rsi state names from "syndiemothroach" to "syndimothroach".

Fix syndimothroach rsi state names.

---

Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Resources/Prototypes/Roles/Jobs/Science/borg.yml
Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Resources/Prototypes/Roles/Jobs/Science/scientist.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml

Raises role timers to a more appropriate amount of hours, with 2 caveats:
- The timers are lower than the ones found on Wizden servers to ease the grind. Feedback is appreciated.
- As Cargo Technicians are able to buy anything, including dangerous goods, as well as sell items to the detriment of the station, the Cargo Technician role is locked behind a 1 hour overall playtime requirement, the same amount of time required to play as a technical assistant.
There are times people playing more sensitive jobs are handling their roles poorly, because they are too new to be able to play their roles properly. We don't want a security officer to kill a surrendering traitor instead of arresting them. We don't want the chief medical officer to not know how to do meds properly. We don't want the …

Raise role timers.

---

Resources/Prototypes/Entities/Mobs/NPCs/space.yml

Snail blood changed to blue blood instead of cryoxadone
Why would snails have cryoxadone as blood?

Update space.yml - Snail blood to blue blood

---

Resources/Prototypes/GameRules/events.yml

Changes the rarity of certain events
Makes events less common, certain ones only happen if the player count is 5 or higher

Makes certain events less common

---

Resources/Prototypes/GameRules/pests.yml

Changes the rarity of pest migration events
Makes migrations less common

Make pest migration chances lower

---

Resources/Locale/en-US/ronstation/objectives/conditions/steal-target-groups.ftl
Resources/Prototypes/Ronstation/Objectives/stealTargetGroups.yml

Adds a locale for the salvage shuttle console board objective, then tweaks the `stealTargetGroups.yml` to fit in that.
https://github.com/space-wizards/space-station-14/pull/30153 caused the current system to become quickly outdated, causing errors in return. As a result, we have to add a locale to fix these errors.
The errors:
**Changelog**
- add: Added locale for salvage shuttle console board steal objective.
- fix: Updated the `stealTargetGroups.yml` to prevent errors from occurring.

Fix salvage shuttle localization issue.

---

Resources/Locale/en-US/reagents/meta/fun.ftl
Resources/Prototypes/Reagents/fun.yml
Resources/Prototypes/Recipes/Reactions/fun.yml

Adds ammoniated sludge, which makes you scream, that's it
Fun.

Ammoniated Sludge

---

Resources/Prototypes/GameRules/variation.yml

Makes ammoniated sludge spawn roundstart on the floor

Adds ammoniated sludge to variation.yml

---

Resources/Prototypes/Entities/Objects/Specific/Medical/randompill.yml

Puts new chems into maintenance pill table.
**Merge other pulls before merging this one**

Tweaks strange pills

---

Resources/Prototypes/Reagents/fun.yml

title
you can make people infinitely scream if you use fluorosurfactant

metabolism rate for ammoniated sludge

---

Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
Resources/Prototypes/NPCs/goliath.yml

goliath hp 250 -> 175
goliath stun duration 5 -> 2
goliath dmg 20 (10/10) -> 12 (6/6)
goliath vision radius 6 -> 8
goliath aggro radius 10 -> 12
goliath tentacle range 10 -> 12
goliath tentacle cooldown 8 -> 4
adds a gauze to salvage lockers to help fighting against hivelords
makes fighting against goliaths actually viable and not a somewhat suicide
rah
nun.
nun.
**Changelog**
Goliaths are now actually fun to fight against.

goliath rebalance

---

Resources/Maps/Ronstation/Shuttles/emergency_small.yml

Expands NT Evac Small shuttle's engineering room and fitted another 15 kilowatts generator to the NT Evac Small shuttle.
One round, it was discovered to have an embarrassing flaw, where there wouldn't be enough power to power the entire shuttle. This, along with the lack of light, made the shuttle horrible for people, as the firelocks won't function and the emergency shuttle console won't function as well.
**Changelog**
:cl: Merrokitsune
- tweak: NT Evac Small shuttle has an expanded engineering room.
- fix: Added another 15 kilowatts generator to the NT Evac Small shuttle.

Fitted another 15 kilowatts generator to the NT Evac Small shuttle.

---

Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml

Self-explanatory: replaces air tanks in lockers with oxygen and nitrogen tanks.
This change is meant to accomodate Vox, a species that, unlike slimes, will get damage when they breathe oxygen, and as such cannot breathe with air tanks, which has both nitrogen and oxygen.
**Changelog**
:cl:
- tweak: Lockers now have oxygen and nitrogen tanks instead of air tanks.

Replace air tanks in lockers with oxygen and nitrogen tanks.

---

Content.Server/Solar/Components/SolarPanelComponent.cs

changes solars so it produces power at a reasonable number
wizden moment

solar power buff

---

Resources/Prototypes/Reagents/chemicals.yml

Regroups chems
Fixes, i think.

regroups chems, some other changes

---

Resources/Prototypes/Reagents/chemicals.yml

Reverts RonRonstation/ronstation#125

Reverts "regroups chems, some other changes"

---

Resources/Maps/Ronstation/Shuttles/emergency_medium.yml
Resources/Maps/Ronstation/Shuttles/emergency_small.yml

- Added screens for evac small and evac medium.
- Removed chairs blocking firelocks from closing.
- Evac small and evac medium seem to be lacking the screen that shows how long until round-end.
- Chairs are blocking firelocks from closing. Imagine, in an event of spacing, that the rooms will still get spaced because the firelocks failed to close.
Note: the evac screens do not show the time for some reason.
Evac small:
Evac medium:
**Changelog**
:cl:
- add: Added screens for evac small and evac medium.
- fix: Removed chairs blocking firelocks from closing.

Shuttle modifications.

---

Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
Resources/Prototypes/Entities/Objects/Decoration/present.yml

Adds some spawns for poker cards to spawn, so the games vending machine doesn't become the only way for poker cards to spawn.
I noticed some maps don't have game vending machines. So, some more spawns are needed.
**Changelog**
:cl:
- add: Poker cards now have more ways to spawn, than only by being dropped by poker machines.

Add spawns for poker cards.

---

Resources/Prototypes/Maps/Pools/default.yml

Removes Reach from being rotated.
Reach, a revival of an ancient map of the same name, is surprisingly unsuitable to be used as a map. This map lacks enough grate liners to protect it's windows from even dust storms (thus causing way too many hull breaches by those events), has an atmos that is too barebones, a layout that is confusing (e.g. why is engineering and atmospherics so separated from each other?, why do you have to go to security to access the bridge?), a way too boring engine setup (yes, having an infinite generator sounds nice, but it's getting boring, is it?), no salvage shuttle console (the result of that pr that removed the salvage shuttle), a lack of not only intern roles, but also heads of staff roles, and some other annoying features and band-aids (e.g. why is there a …

Derotate Reach.

---

Resources/Locale/en-US/reagents/meta/elements.ftl
Resources/Locale/en-US/reagents/meta/fun.ftl
Resources/Locale/en-US/reagents/meta/medicine.ftl
Resources/Locale/en-US/reagents/meta/narcotics.ftl
Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
Resources/Prototypes/Reagents/chemicals.yml
Resources/Prototypes/Reagents/elements.yml
Resources/Prototypes/Reagents/fun.yml
Resources/Prototypes/Reagents/medicine.yml
Resources/Prototypes/Reagents/narcotics.yml
Resources/Prototypes/Reagents/toxins.yml
Resources/Prototypes/Recipes/Reactions/fun.yml
Resources/Prototypes/Recipes/Reactions/medicine.yml

Rewrite of #138, orders, fixes, perfects some new chemicals.
1. Bromine (reagent for future chemicals)
2. Magnesium (reagent for future chemicals)
3. Platinum (reagent for future chemicals)
4. Calcium (reagent for future chemicals)
5. Barium (reagent for future chemicals)
6. Helium (reagent for future chemicals)
7. Caffeine
8. Salicyclic Acid
9. Salbutamol

More chemicals part five

---

Resources/Maps/Ronstation/saltern-2.yml

The main area outside of the dormitory itself has been changed from a games area to being more focused on the theme of a break room. This includes a complete tile rework and entirely new furnishings as well as some emergency closets. These changes were made because the area is redundant and mostly unused due to the presence of social and games environments being provided by the bar and library already which see more frequent use. This area can instead be used to destress and take a break from the chaos of the shift.
This will not affect game balance in any significant way. People might find it easier to run through this area, making evading others easier. The inclusion of emergency gear might also make it easier to survive environmental disaster.
There should be no code changes present. …

Changes the dormitory.

---

Resources/Maps/Ronstation/saltern-2.yml

Because of the recent changes to the bridge, the docking station for Cargo was broken and its functionality reduced. This update fixes this and gives some more back to Cargosians by expanding Cargo by some margin and tweaking its layout to make their jobs and lives easier. Additionally, chairs were added to the Bridge. I made sure to consult with someone who had experience with cargo when making these tweaks.
From start to finish, the trip to and from the front desk to the cargo shuttle is longer but not by much. Maybe the addition of a second Cargo Request Terminal would help. As for other balance changes, cargo now has more room to process crates and build machines to help fulfill orders in-house. 
There should be no code changes
There should be no breaking changes.
**Changelog**
:cl: …

Updates Cargo to fix an error and improve it a little.

---

Resources/Prototypes/Entities/Objects/Misc/spaceshroom.yml
Resources/Prototypes/Procedural/biome_templates.yml

Adds space mushrooms to (some) planets, changes chemicals.
Parity with SS13 mechanics, sort of.

Procedural Planets now generate mushrooms

---

LICENSE.TXT

Adds a bit of text clarifying ownership of Ronstation's contributions to the code.
We noted how only the Space Wizards Federation appears to be listed in the license here. This makes an addition to the text stating that the ownership of some of the code belongs to the contributors, as well as the Ronstation Team with their contributions.
**Changelog**
:cl:
- fix: Fixed license.

Fix licensing.

---

Resources/Maps/Ronstation/Shuttles/ShuttleEvent/ERTcburn.yml

quickiest quicky fix ever

---

Resources/Prototypes/Ronstation/Entities/Objects/Devices/pda.yml

Fixes PDA error.
New update that adds chameleon PDAs caused issues with our custom content PDAs. Luckily, localhost still can run, despite the issue.
**Changelog**
:cl:
- fix: Temporarily resprited blueshield and heccdiver PDAs to the few available in upstream `pda.rsi` folder, pending rework.

Hotfix PDA error.

---

Resources/Prototypes/Entities/Objects/Misc/bedsheets.yml

Allows mothpeople to eat bedsheets.
Would it be funny if a thief tries to get their hands on a bedsheet, only to be eaten by some mothroach (or even themselves if they're a moth) and has to go to the Head of Personnel to print bedsheets for them?
**Changelog**
:cl:
- tweak: Bedsheets can be eaten by moths.

Make bedsheets eatable by moths.

---

LEGAL.md
LICENSE-MIT.TXT
README.md

Relicenses Ronstation to AGPL-v3.0.
- To allow easier porting to Ronstation of not only other AGPL v3.0-licensed forks, but also SS13 codebases such as https://github.com/tgstation/tgstation.
- AGPL-v3.0 is found to be beneficial, which is forcing any improvements of their code to remain licensed under AGPL-v3.0, allowing us to remain under AGPL-v3.0.
- The free software foundation, the makers of AGPL-v3.0, can be contacted to become legal counsel in the event of a license breach.
If you have a closed-source fork of Ronstation, you are not legally allowed to use any code submitted to Ronstation after the license change, unless you release the source code for your fork under the AGPLv3 license to any person who can connect to your server. If you are a contributor, you agree to license the …

Relicense all future ronstation content to agpl v3.0 

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

Have changed the role information to be a free agent.
This will add more roleplay potential for people who would want it but the AI will still attack as requested in the suggestion.
https://discord.com/channels/1133379746361770034/1344090101101367376
Replaced the red and Team Antagonist to yellow and Free Agent.
**Changelog**
tweak: Changed ghost role component.

Changed spider ghost role to be free agent

---

.run/Content Server+Client.run.xml
Resources/Prototypes/Ronstation/Maps/atlas-2.yml

fixes lawyer job on atlas

---

Resources/Prototypes/Catalog/spellbook_catalog.yml

Disables event spells.
These spells not only give you goodies, but they also turn everyone into free agents, resulting in a NRP festival of unnecessary and unimmersive cacophony. This disables event spells.
**Changelog**
:cl:
- remove: Removed event spells.

Disable event spells.

---

Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml

**Changelog**
:cl:
- fix: Readded oxygen and nitrogen tanks to engineer and atmos lockers with hardsuits.

Readd gas tanks to engineer lockers.

---

Content.Shared/CCVar/CCVars.Server.cs
Resources/Prototypes/Guidebook/rules.yml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC0.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC1.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC10.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC2.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC3.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC4.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC5.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC6.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC7.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC8.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/CoreRules/RuleC9.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR0.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR1.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR2.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR3.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR4.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR5.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR6.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RoleplayRules/RuleR7.xml
Resources/ServerInfo/Guidebook/ServerRules/Ronstation/RonstationRules.xml

The rules.
The rules needed changed.
No changes were made.
It does not break. It creates.
**Changelog**
:cl:
- add: Rules
- remove: Rules
- fix: Rules
- tweak: Rules

Rules Change

---

Resources/Prototypes/Ronstation/Entities/Mobs/Player/humanoid.yml

Fixes bug in heccdiver and blueshield officer names.
YAML error cause.
**Changelog**
:cl:
- Fix: Fixed heccdiver names.
- Fix: Fixed blueshield officer names.

Fix heccdiver and CC blueshield names.

---

Resources/Prototypes/Entities/Objects/Specific/chemistry.yml

Beakers now have more space. Outlined below:
Beaker and Robot Beaker: 50 to 60 (10u increase)
Large Beaker: 100 to 120 (20u increase)
The main reason for the change is so chemist don't have to spend more time mixing and changing beakers. Since chems usually have 2-3 mixtures, this should allow easier mixing without the pushback of the limits that are based on 5s instead of 3s/6s.
I changed values only, as well as a single description for the robot version.
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.
This should break nothing, all it does is change values.
**Changelog**
:cl:
- …

Increased Beaker Capacity

---

Resources/Prototypes/Recipes/Lathes/Packs/cargo.yml

Removes the ability to print Circuit Imprinters on autolathes.
I initially merged it with the assumption that I can do a rimworld event, now that we looked further into it, it seems too redundant and a bit powergamey.
I might toy around new ideas to allow it to become “rimworld compatible”, but a circuit imprinted should not be too easy to get.
**Changelog**
:cl:
- remove: Removed lathes ability to print circuit imprinters.

Remove imprinter from lathe pack.

---

Resources/Prototypes/Atmospherics/gases.yml
Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/artifact_equipment.yml

Balanced Gases prices for manufactured gases and added the Sell Override (Science) to the Artifact Container.
Trit Sell Price:  3 -> 2
Frezon Sell Price;  7 -> 5
To Reduce the amount gained from the Frezconomy and allow science to recoup artifact costs.

Gas Price Balance

---

Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/engines.yml
Resources/Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/production.yml
Resources/Prototypes/_Ronstation/Entities/Objects/Devices/Circuitboards/Machine/production.yml

Removed requirements of using removed machine parts.
Some machine parts, especially the matter bin and capacitor, have been removed by upstream. This affected our custom content, so I did a fix.
**Changelog**
:cl:
- Remove: Removed requirements of using removed machine parts.

Remove requirements of using removed machine parts.

---

Resources/Prototypes/Magic/touch_spells.yml

- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**

Fix C.Smite to remove unneeded components/fit the new format for spell actions

---

LEGAL.md
LICENSE-MIT.TXT
README.md

Ports a modified version of https://github.com/DeltaV-Station/Delta-v/pull/3989.
1. Basically, the main differences would be the addition of subfolders, with appropriate license text attached.
2. Clarified what is subject to being sublicensed as MIT + AGPL v3.0 and mere MIT. In this case, any MIT-licensed code, including those from upstream, will remain MIT-Licensed, unless modified, in which case it gets sublicensed as MIT + AGPL v3.0 from the space wizards federation. An “unless otherwise stated” text is provided in the event the author provides such statements in a PR.
3. This may be used in conjunction with simple annotations to provide clarity.
Also removed potential legal quagmire in MIT license text.
Made as part of approach 2 in …

Clarification of licenses 

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Locale/en-US/tools/tool-qualities.ftl
Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/seeds.yml
Resources/Prototypes/Catalog/spellbook_catalog.yml
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
Resources/Prototypes/Entities/Objects/Misc/paper.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
Resources/Prototypes/Entities/Stations/base.yml
Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/Recipes/Lathes/Packs/biogen.yml
Resources/Prototypes/Tiles/plating.yml
Resources/Prototypes/_Ronstation/tool_qualities.yml
Resources/Prototypes/tool_qualities.yml

Adds license headers and comments showing where Ronstation contributors have made changes to upstream content. Migrates content to _Ronstation sub-directories where possible.
Adds comments to/reorganizes files from the following PRs:
https://github.com/RonRonstation/ronstation/pull/199
https://github.com/RonRonstation/ronstation/pull/196
https://github.com/RonRonstation/ronstation/pull/195
https://github.com/RonRonstation/ronstation/pull/193
https://github.com/RonRonstation/ronstation/pull/190
https://github.com/RonRonstation/ronstation/pull/187
https://github.com/RonRonstation/ronstation/pull/186
https://github.com/RonRonstation/ronstation/pull/185
https://github.com/RonRonstation/ronstation/pull/184
This is a continuation of PR https://github.com/RonRonstation/ronstation/pull/297, …

The Great Reorganization PT 4

---

Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_special.yml

Increased DrinkShaker and DrinkTeapot from 100u to 120u
Beakers were previously increased, and this also makes the solution cleanly dividable into 4 full cups, instead of 3.3333333
Just increased the capacity and in Teapot's case the solution too to 120u
**Changelog**
- tweak: Increased shaker and teapot capacity from 100u to 120u

DrinkShaker and DrinkTeapot now are 120u instead of 100u

---

Resources/Maps/_Ronstation/atlas-3.yml

Hotfixes for Atlas-IIV based on the forum thread.
Playable map is good map.
Edited serialized map.

Atlas 3 hotfixes

---

LEGAL.md

Cosmatic Drift attribution

---

Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs
Content.Shared/Roles/AntagPrototype.cs
Content.Shared/Roles/JobRequirement/RoleTimeRequirement.cs
Content.Shared/Roles/Jobs/SharedJobSystem.cs
Content.Shared/Roles/SharedRoleSystem.cs
Resources/Locale/en-US/_Ronstation/job/job-names.ftl
Resources/Prototypes/Roles/Antags/changeling.yml
Resources/Prototypes/Roles/Antags/dragon.yml
Resources/Prototypes/Roles/Antags/generic.yml
Resources/Prototypes/Roles/Antags/ninja.yml
Resources/Prototypes/Roles/Antags/nukeops.yml
Resources/Prototypes/Roles/Antags/paradoxClone.yml
Resources/Prototypes/Roles/Antags/revolutionary.yml
Resources/Prototypes/Roles/Antags/silicon.yml
Resources/Prototypes/Roles/Antags/thief.yml
Resources/Prototypes/Roles/Antags/traitor.yml
Resources/Prototypes/Roles/Antags/wizard.yml
Resources/Prototypes/Roles/Antags/zombie.yml
Resources/Prototypes/_Ronstation/Roles/Antags/vampire.yml
Resources/Prototypes/_Ronstation/Roles/play_time_trackers.yml

Original credit to https://github.com/space-wizards/space-station-14/pull/33228
Lets us use antag playtime requirements!
Added PlayTimeTracker field to AntagPrototype, made SharedJobSystem tracker update time tracker from it too, utilized it in the SharedRoleSystem, and made JobRequirementsManager fetch antag playtime too
Also added trackers for each antag and added them too the antags
These are examples of antag time requirements, this PR doesn't make any changes to any time requirements, but adds support for that in the future
**Changelog**
:cl:
- add: Implemented antag role time trackers!

Implement antag playtime tracking

---

Resources/Maps/_Ronstation/atlas-3.yml

Adresses issues logged in the forum thread.

Another Atlas 3 patch

---

Content.Client/Pinpointer/UI/NavMapControl.cs
Content.Client/Silicons/StationAi/StationAiOverlay.cs

Replaced the horrible static noise in areas not covered by cameras for sAI with a navmap instead.
98% reduction in filesize of sAI gameplay recordings, as there is no longer bitrate consuming noise.
This makes sAI gameplay recording and streaming a LOT better.
Also reduces general sAI disorientation when eye gets lost in maints
Copied some render code from NavMapControl and added a NavMapControl instance to StationAiOverlay
https://github.com/user-attachments/assets/366611ee-dfdc-438c-b894-229ca7a075c1
**Changelog**
:cl:
- tweak: Replaced static noise for sAI with a navmap!

AI navmap done right

---

Content.Client/Lobby/LobbyUIController.cs
Content.Server/Station/Systems/StationSpawningSystem.cs
Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/_Ronstation/Loadouts/Groups/Science/borg.yml
Resources/Prototypes/_Ronstation/Loadouts/Role/Science/borg.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/arachind.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/atmosian.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/bee.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/diona.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/hampter.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/human.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/lizard.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/moth.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/nuke.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/penguin.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/slime.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/space_lizard.yml
Resources/Prototypes/_Ronstation/Loadouts/Trinkets/Plushies/vox.yml

Cloned the trinket plushies loadout, left only the plushies can wear as a hat, and changed equip slot from backpack to hat!
Requirements are shared with the original trinket loadouts
**Changelog**
:cl:
- tweak: Borgs can now choose a plushie to spawn with on their head!

Let borgs equip trinket plushies in loadouts!

---

Resources/Prototypes/Species/species_weights.yml
Resources/Prototypes/Species/vulpkanin.yml

Vulp are disabled as a roundstart species.
I was asked to.
**Changelog**
:cl:
- remove: Vulpkanin are removed as a roundstart species.

Disables Vulpkanin

---

Resources/Prototypes/Species/species_weights.yml
Resources/Prototypes/Species/vulpkanin.yml

Reverts RonRonstation/ronstation#404
Title.
Viva.

Enables Vulpkanin

---

Resources/Prototypes/Entities/Structures/Furniture/toilet.yml

Removed edible component from toilet so you can't drink out of it anymore.
Is just a bit too gross for us.
N/A
**Changelog**
:cl:
- tweak: You can't drink out of toilets anymore.

Do NOT drink outta da toiler 

---

Resources/Prototypes/Voice/speech_emote_sounds.yml

Changed the vulpkanin scream to use the default screaming noises instead.
The current sounds sound a bit too much like a kicked dog. This will be good enough until we can find a suitable replacement.
**Changelog**
:cl:
- tweak: Vulpkanin use the default male/female screams instead of their unique ones (for now).

Change Vulp Scream to default scream
